### ISSUE TITLE
onDisable error

### ISSUE THREAD

**Issue by ImNotStable** [AyhamAl-Ali/TuSKe2#2]
Error occurred while disabling TuSKe v2.1 (Is it up to date?)
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
        at com.github.tukenuke.tuske.manager.gui.v2.SkriptGUIEvent.<init>(SkriptGUIEvent.java:28) ~[TuSKe2.jar:?]
        at com.github.tukenuke.tuske.manager.gui.v2.SkriptGUIEvent.getInstance(SkriptGUIEvent.java:24) ~[TuSKe2.jar:?]
        at com.github.tukenuke.tuske.TuSKe.onDisable(TuSKe.java:120) ~[TuSKe2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:555) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.disablePlugins(CraftServer.java:494) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:972) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:803) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1271) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Server Version: git-Paper-386 (MC: 1.18.2)
Skript Version: 2.6.2
Installed Skript Addons:
 - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
 - Skacket v1.0.10
 - Skellett v2.0.6 (https://forums.skunity.com/resources/skellett.24/)
 - Diskuise v0.2-beta3
 - SkQuery v4.1.6
 - SkBee v1.16.2 (https://github.com/ShaneBeee/SkBee)
 - SkJade v1.4.1 (https://www.github.com/Ankoki-Dev/SkJade)
 - Khoryl v1.0.5
 - TuSKe v2.1 (github.com/Tuke-Nuke/TuSKe)
Installed dependencies:
 - Vault v1.7.3-b131

**Comment by ImNotStable** [comment]
@AyhamAl-Ali

**Comment by AyhamAl-Ali** [comment]
Sorry for being late, for some reason I wasn't watching this repo. 

Tuske isn't supposed to work with Skript 2.6+*yet* not sure if I will support that soon but I have it in my todo list

**Comment by AyhamAl-Ali** [comment]
For the mean time I suggest using skript-gui for gui stuff to work with new Skript versions

**Comment by ImNotStable** [comment]
Alright it's completely fine and I understand I appreciate you replying and helping with Skript. The reason I don't use Skript-gui is I don't like the syntax.

**Comment by AyhamAl-Ali** [comment]
Thank you for helping and reporting bugs I appreciate that \:D 
Hopefully soon I can get Tuske2 ready for Skript 2.6+
